server:
  port: '9090'

spring:
  redis:
    host: localhost
    port: '6379'
  cache:
    redis:
      cache-null-values: false
      time-to-live: '600000'

covid:
  api:
    url: 'https://covid-api.mmediagroup.fr/v1'
    cases:
      endpoint: '/cases'
    vaccines:
      endpoint: '/vaccines'
